Update cmsplit_type.c to add tests for communicator unguided split case
open-mpi/ompi-tests-public pull request #23
Opened 2022-09-19 18:33 UTC by drwootton

Update the cmsplit_type.c  testcase to add tests for the unguided communicator split 
(MPI_COMM_TYPE_HW_UNGUIDED) case.

Signed-off-by: David Wootton <dwootton@us.ibm.com>

2022-09-19 19:14 UTC, gpaulsen commented
Requires this PR to pass: https://github.com/open-mpi/ompi/pull/10739

2022-09-30 12:11 UTC, jsquyres commented
Rebased to get the new GitHub Action CI test.

2022-10-10 20:58 UTC, jjhursey requested changes
1 note but otherwise it looks fine.

2022-10-10 20:58 UTC, jjhursey commented on comm_split_type/cmsplit_type.c
> +#if 0
Why is this `MPI_COMM_TYPE_HW_GUIDED` test commented out? It should work.

2022-10-12 14:01 UTC, jjhursey approved these changes

2022-10-12 14:02 UTC, merged